language: node_js

node_js:
  - "12"

os:
  - linux

sudo: false

rvm:
  - 2.2.0

cache:
    npm: false
    directories:
        - $HOME/.npm

# env:
#   global:
#     - CC_TEST_REPORTER_ID=2770352d161fdd7e1530feeff3c71a5d7f0c45550bdad619f24096fdb36e9a25

install:
  - npm install  
  - npm install jasmine-node

# before_script:
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build

script:
  - npm run coverage                    

# after_script:
#   - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
#   - ./cc-test-reporter upload-coverage

